@server = http://localhost:8080
###
GET {{server}}/api/instrumentos
### 
POST {{server}}/api/instrumentos
Content-Type: application/json

{"firstName": "Mi" ,"lastName":"Aplicacion","description":"React"}